name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build
        run: |
          npm install
          grunt build
          grunt compress

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: theme-package
          path: dist/*.zip
          retention-days: 7
